services:
  # Aplicação Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: www
        uid: 1000
    container_name: br-municipios-api
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - br-municipios-api
    depends_on:
      - redis
    env_file:
      - .env.docker
    environment:
      - REDIS_HOST=redis

  # Servidor Web (Nginx)
  webserver:
    image: nginx:alpine
    container_name: br-municipios-api-webserver
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - br-municipios-api
    depends_on:
      - app

  # Redis (Cache)
  redis:
    image: redis:alpine
    container_name: br-municipios-api-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - br-municipios-api

networks:
  br-municipios-api:
    driver: bridge

volumes:
  redis_data:
    driver: local
