name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Tests & Code Quality
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, redis
          coverage: xdebug

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Setup Laravel
        run: |
          cp .env.example .env
          php artisan key:generate
          touch database/database.sqlite
          php artisan migrate --force

      - name: Code Quality - Laravel Pint
        run: vendor/bin/pint --test

      - name: Run Tests
        run: |
          php artisan config:clear
          vendor/bin/phpunit --coverage-text

  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/br-municipios-api
            
            # Backup atual
            sudo cp -r . ../backup-$(date +%Y%m%d-%H%M%S) || true
            
            # Atualizar código
            git pull origin main
            
            # Parar containers atuais
            make down || true
            
            # Rebuild e restart com Docker
            make restart
            
            # Executar migrações via container
            make migrate
            
            # Limpar caches via container
            make cache-clear
            
            # Verificar status
            make status
